/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import conect.IncluirEditarDAO;
import Model.Fornecedores;
import java.util.Date;

/**
 *
 * @author marco
 */
public class jifCadastroFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifCadastroFornecedor
     */
    public jifCadastroFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jtxtCodForn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtRazaoSocial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtData = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jtxtCnpj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtRua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtNumero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtCep = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jbtnNovo = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jrAtivo = new javax.swing.JRadioButton();
        jrInativo = new javax.swing.JRadioButton();
        jtxtCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtEstado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Fornecedor");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jtxtCodForn.setEditable(false);
        jtxtCodForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodFornActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Cód.");

        jtxtRazaoSocial.setEnabled(false);

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Razão Social:");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Data de Cadastro:");

        jtxtCnpj.setEnabled(false);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("CNPJ:");

        jtxtEmail.setEnabled(false);

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("E-mail:");

        jtxtTelefone.setEnabled(false);

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Telefone:");

        jtxtRua.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Endereço");

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Rua:");

        jtxtNumero.setEnabled(false);

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("N°:");

        jtxtBairro.setEnabled(false);

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Bairro:");

        jtxtCep.setEnabled(false);

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Cep:");

        jbtnNovo.setText("Novo");
        jbtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovoActionPerformed(evt);
            }
        });

        jbtnEditar.setText("Editar");
        jbtnEditar.setEnabled(false);

        jbtnSalvar.setText("Salvar");
        jbtnSalvar.setEnabled(false);
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });

        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrAtivo);
        jrAtivo.setText("Ativo");

        buttonGroup1.add(jrInativo);
        jrInativo.setText("Inativo");

        jtxtCidade.setEnabled(false);

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Cidade:");

        jtxtEstado.setEnabled(false);

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Estado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSair)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(211, 211, 211)
                            .addComponent(jLabel13))
                        .addComponent(jLabel7)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtCodForn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jtxtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jtxtData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jtxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel5))
                                            .addGap(65, 65, 65)
                                            .addComponent(jLabel10)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jtxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(99, 99, 99)
                                            .addComponent(jLabel11))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jrAtivo)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jtxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jtxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtCep)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jrInativo))))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtnNovo)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnEditar)
                            .addGap(18, 18, 18)
                            .addComponent(jbtnSalvar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtData, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtCodForn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(jtxtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtBairro)
                    .addComponent(jtxtCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNovo)
                    .addComponent(jbtnEditar)
                    .addComponent(jbtnSalvar)
                    .addComponent(jrAtivo)
                    .addComponent(jrInativo))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSair)
                    .addComponent(jbtnCancelar))
                .addGap(17, 17, 17))
        );

        setBounds(300, 150, 768, 508);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCodFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodFornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodFornActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        jfPrincipal.estoque = true;
        jrAtivo.setSelected(true);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        
        jfPrincipal.estoque = false;
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSairActionPerformed

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed
       
    }//GEN-LAST:event_jbtnSalvarActionPerformed

    private void jbtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovoActionPerformed
        
        novo();
        Date dataSistema = new Date();
        jtxtData.setDate(dataSistema);

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnNovoActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed

        cancelar();

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnNovo;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JRadioButton jrAtivo;
    private javax.swing.JRadioButton jrInativo;
    private javax.swing.JTextField jtxtBairro;
    private javax.swing.JTextField jtxtCep;
    private javax.swing.JTextField jtxtCidade;
    private javax.swing.JTextField jtxtCnpj;
    private javax.swing.JTextField jtxtCodForn;
    private com.toedter.calendar.JDateChooser jtxtData;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtEstado;
    private javax.swing.JTextField jtxtNumero;
    private javax.swing.JTextField jtxtRazaoSocial;
    private javax.swing.JTextField jtxtRua;
    private javax.swing.JTextField jtxtTelefone;
    // End of variables declaration//GEN-END:variables


public void novo (){
    jtxtRazaoSocial.setEnabled(true);
    jtxtBairro.setEnabled(true);
    jtxtCep.setEnabled(true);
    jtxtCnpj.setEnabled(true);
    jtxtCodForn.setEnabled(false);
    jtxtNumero.setEnabled(true);
    jtxtRua.setEnabled(true);
    jtxtTelefone.setEnabled(true);
    jrAtivo.setEnabled(true);
    jtxtEmail.setEnabled(true);
    jtxtCidade.setEnabled(true);
    jtxtEstado.setEnabled(true);
    jbtnEditar.setEnabled(true);
    jbtnSalvar.setEnabled(true);
    jtxtRazaoSocial.setText("");
    jtxtBairro.setText("");
    jtxtCep.setText("");
    jtxtCnpj.setText("");
    jtxtCodForn.setText("");
    jtxtNumero.setText("");
    jtxtRua.setText("");
    jtxtTelefone.setText("");
    jtxtEmail.setText("");
    jtxtCidade.setText("");
    jtxtEstado.setText("");
    
}// fim metodo novo

public void cancelar(){
    jtxtRazaoSocial.setEnabled(false);
    jtxtBairro.setEnabled(false);
    jtxtCep.setEnabled(false);
    jtxtCnpj.setEnabled(false);
    jtxtCodForn.setEnabled(false);
    jtxtNumero.setEnabled(false);
    jtxtRua.setEnabled(false);
    jtxtTelefone.setEnabled(false);
    jrAtivo.setEnabled(false);
    jtxtEmail.setEnabled(false);
    jtxtCidade.setEnabled(false);
    jtxtEstado.setEnabled(false);
    jbtnEditar.setEnabled(false);
    jbtnSalvar.setEnabled(false);
    
    jtxtRazaoSocial.setText("");
    jtxtBairro.setText("");
    jtxtCep.setText("");
    jtxtCnpj.setText("");
    jtxtCodForn.setText("");
    jtxtNumero.setText("");
    jtxtRua.setText("");
    jtxtTelefone.setText("");
    jtxtEmail.setText("");
    jtxtCidade.setText("");
    jtxtEstado.setText("");
    jtxtData.setDate(null);
}


}// fim da classe principal
